#include "display/AircraftSprites.h"

namespace
{
    // ── Sprite bitmaps (generated by tools/sprite_workbench.py) ────────────
    const char *const kNarrowbody[] = {
        "...............................rrr....",
        "..............................rrRR....",
        ".............................rrRRR....",
        "............................rrRRRR....",
        "...........................rrRRRRR....",
        ".....######################rRRRRRR....",
        "...##cc#w#w#w#w#w#w#w#w#w#w#w##RRRRggg",
        "..########################d######gggg.",
        ".#################################+g..",
        ".+++++++++++++++++++++++++++++++++....",
        "...++++++gggggggg++++++++++++.........",
        "........ggggggggggg...................",
        ".........eeeeedd......................",
        ".........eeeeddd......................",
    };
    const char *const kWidebodyTwin[] = {
        "...................................rrr.....",
        "..................................rrRR.....",
        ".................................rrRRR.....",
        "................................rrRRRR.....",
        "...............................rrRRRRR.....",
        "..............................rrRRRRRR.....",
        "......########################rRRRRRRR.....",
        "....##cc#w#w#w#w#w#w#w#w#w#w#w#w#w##RRRRggg",
        "..#####################################gggg",
        ".######################################+g..",
        "#######################################....",
        ".++++++++++++++++++++++++++++++++++++......",
        "....++++++gggggggggg++++++++++++++.........",
        "..........ggggggggggggg....................",
        ".........eeeeeeeddd........................",
        ".........eeeeeeedd.........................",
    };
    const char *const kA380[] = {
        "...................................rrr.....",
        "..................................rrRR.....",
        ".................................rrRRR.....",
        "........########################rrRRRR.....",
        "......##w#w#w#w#w#w#w#w#w#w#w#w#rRRRRR.....",
        ".....###########################RRRRRR.....",
        "....##cc#w#w#w#w#w#w#w#w#w#w#w#w#w##RRRRggg",
        "..#####################################gggg",
        ".######################################+g..",
        "#######################################....",
        ".++++++++++++++++++++++++++++++++++++......",
        "....++++gggggggggggggg+++++++++++..........",
        ".......eeeedd...eeeedd.....................",
        ".......eeeedd...eeeedd.....................",
    };
    const char *const k747[] = {
        "...................................rrr.....",
        "..................................rrRR.....",
        ".....#######.....................rrRRR.....",
        "....##cc#w#w##..................rrRRRR.....",
        "...############................rrRRRRR.....",
        "...#############################RRRRRR.....",
        "..###w#w#w#w#w#w#w#w#w#w#w#w#w#w##RRRRggg..",
        ".######################################gggg",
        "#######################################+g..",
        "#######################################....",
        ".++++++++++++++++++++++++++++++++++++......",
        "....++++gggggggggggggg+++++++++++..........",
        ".......eeeedd...eeeedd.....................",
        ".......eeeedd...eeeedd.....................",
    };
    const char *const kRegionalJet[] = {
        "..........................rrr.",
        ".........................rrRR.",
        "........................rrRRR.",
        ".......................rrRRRR.",
        "....##################rrRRRRR.",
        "..##cc#w#w#w#w#w#w#w#w##RRRRgg",
        ".############################g",
        ".##########################+..",
        ".++++++++++++++++++++++++++...",
        "...+++++ggggggg+++++++........",
        "......ggggggggg...............",
        ".......eeeedd.................",
    };
    const char *const kTurboprop[] = {
        "..............................rr..",
        ".............................rrR..",
        ".....p...gggggggggggggggg...rrRR..",
        ".....pgggeeeedd............rrRRR..",
        ".....p...eeedd.............rRRRR..",
        "....########################RRRRgg",
        "..##cc#w#w#w#w#w#w#w#w#w#w###RRgg.",
        ".#############################+...",
        ".###########################++....",
        ".++++++++++++++++++++++++++.......",
        "........d.........................",
    };
    const char *const kBusinessJet[] = {
        ".................rrrrrrrrr",
        "....................rrRR..",
        "...................rrRR...",
        "..................rRRR....",
        "....###########eeeeddRR...",
        "..##cc#w#w#w##eeeeddRR....",
        ".################++++.....",
        ".##############+++........",
        ".+++++++++++++............",
        "....++ggggggg.............",
    };
    const char *const kHelicopter[] = {
        "ppppppppppppppppppppppppp......",
        "...........dd..................",
        ".........######................",
        "......##########...............",
        "....##ccw#########.............",
        "...#ccww############rrrrrrrrrrR",
        "...################+.......rrRR",
        "....++++++++++++++..........R..",
        ".....d.........d...............",
        "...ddddddddddddddd.............",
    };
    const char *const kLightAircraft[] = {
        ".....gggggggggggggggg...",
        "......#cc#..............",
        "p...#####c##..........r.",
        "p.####################R.",
        "p######################.",
        "p...+++++++++++++.....gg",
        "......d.......d.........",
        ".....ddd.....ddd........",
    };

    template <size_t N>
    constexpr uint8_t rowsOf(const char *const (&)[N]) { return (uint8_t)N; }

#define SPRITE(name, arr) {name, (uint8_t)strlen(arr[0]), rowsOf(arr), arr}
    const AircraftSprites::Sprite kSprites[AircraftSprites::KindCount] = {
        SPRITE("Narrowbody", kNarrowbody),
        SPRITE("Widebody twin", kWidebodyTwin),
        SPRITE("A380", kA380),
        SPRITE("747", k747),
        SPRITE("Regional jet", kRegionalJet),
        SPRITE("Turboprop", kTurboprop),
        SPRITE("Business jet", kBusinessJet),
        SPRITE("Helicopter", kHelicopter),
        SPRITE("Light aircraft", kLightAircraft),
    };
#undef SPRITE

    // ── ICAO type designators ────────────────────────────────────────────────
    // Exact codes first, then prefixes. Codes are matched case-insensitively.
    struct TypeRule { const char *code; AircraftSprites::Kind kind; bool prefix; };
    using K = AircraftSprites::Kind;
    const TypeRule kRules[] = {
        // A380 / 747
        {"A38", K::A380, true},
        {"B74", K::B747, true},
        // Business jets (before the generic Embraer/Cessna/Bombardier prefixes)
        {"E35L", K::Bizjet, false}, {"E50P", K::Bizjet, false}, {"E55P", K::Bizjet, false},
        {"E545", K::Bizjet, false}, {"E550", K::Bizjet, false},
        {"C25",  K::Bizjet, true},  {"C500", K::Bizjet, false}, {"C501", K::Bizjet, false},
        {"C510", K::Bizjet, false}, {"C525", K::Bizjet, false}, {"C550", K::Bizjet, false},
        {"C560", K::Bizjet, false}, {"C56X", K::Bizjet, false}, {"C650", K::Bizjet, false},
        {"C680", K::Bizjet, false}, {"C68A", K::Bizjet, false}, {"C700", K::Bizjet, false},
        {"C750", K::Bizjet, false}, {"CL30", K::Bizjet, false}, {"CL35", K::Bizjet, false},
        {"CL60", K::Bizjet, false}, {"GLF",  K::Bizjet, true},  {"GLEX", K::Bizjet, false},
        {"GL5T", K::Bizjet, false}, {"GL7T", K::Bizjet, false}, {"GL8T", K::Bizjet, false},
        {"G280", K::Bizjet, false}, {"FA",   K::Bizjet, true},  {"F2TH", K::Bizjet, false},
        {"F900", K::Bizjet, false}, {"LJ",   K::Bizjet, true},  {"H25",  K::Bizjet, true},
        {"BE40", K::Bizjet, false}, {"PRM1", K::Bizjet, false}, {"PC24", K::Bizjet, false},
        {"HDJT", K::Bizjet, false}, {"SF50", K::Bizjet, false}, {"EA50", K::Bizjet, false},
        {"ASTR", K::Bizjet, false}, {"GALX", K::Bizjet, false},
        // Widebody twins (and other widebodies, which share the profile)
        {"A30",  K::WidebodyTwin, true}, {"A31",  K::WidebodyTwin, true},   // A300/A310 (A318/A319 below)
        {"A33",  K::WidebodyTwin, true}, {"A34",  K::WidebodyTwin, true},
        {"A35",  K::WidebodyTwin, true}, {"B76",  K::WidebodyTwin, true},
        {"B77",  K::WidebodyTwin, true}, {"B78",  K::WidebodyTwin, true},
        {"MD11", K::WidebodyTwin, false}, {"DC10", K::WidebodyTwin, false},
        {"IL96", K::WidebodyTwin, false},
        // Narrowbodies (A318/A319 before the A31 widebody prefix catches them)
        {"A318", K::Narrowbody, false}, {"A319", K::Narrowbody, false},
        {"A32",  K::Narrowbody, true},  {"A19N", K::Narrowbody, false},
        {"A20N", K::Narrowbody, false}, {"A21N", K::Narrowbody, false},
        {"B73",  K::Narrowbody, true},  {"B37M", K::Narrowbody, false},
        {"B38M", K::Narrowbody, false}, {"B39M", K::Narrowbody, false},
        {"B3XM", K::Narrowbody, false}, {"B75",  K::Narrowbody, true},
        {"B712", K::Narrowbody, false}, {"BCS",  K::Narrowbody, true},
        {"MD8",  K::Narrowbody, true},  {"MD90", K::Narrowbody, false},
        {"C919", K::Narrowbody, false},
        // Regional jets
        {"E17",  K::RegionalJet, true}, {"E19",  K::RegionalJet, true},
        {"E29",  K::RegionalJet, true}, {"E75",  K::RegionalJet, true},
        {"E13",  K::RegionalJet, true}, {"E14",  K::RegionalJet, true},
        {"CRJ",  K::RegionalJet, true}, {"RJ",   K::RegionalJet, true},
        {"B46",  K::RegionalJet, true}, {"SU95", K::RegionalJet, false},
        {"F70",  K::RegionalJet, false}, {"F100", K::RegionalJet, false},
        // Turboprops
        {"AT4",  K::Turboprop, true},   {"AT7",  K::Turboprop, true},
        {"DH8",  K::Turboprop, true},   {"DHC6", K::Turboprop, false},
        {"SF34", K::Turboprop, false},  {"JS41", K::Turboprop, false},
        {"JS32", K::Turboprop, false},  {"D328", K::Turboprop, false},
        {"SB20", K::Turboprop, false},  {"F50",  K::Turboprop, false},
        {"B190", K::Turboprop, false},  {"BE20", K::Turboprop, false},
        {"BE9L", K::Turboprop, false},  {"B350", K::Turboprop, false},
        {"L410", K::Turboprop, false},  {"PC12", K::Turboprop, false},
        {"C208", K::Turboprop, false},  {"TBM",  K::Turboprop, true},
        {"P180", K::Turboprop, false},  {"BN2",  K::Turboprop, true},
        {"C130", K::Turboprop, false},  {"A400", K::Turboprop, false},
        // Helicopters
        {"EC",   K::Helicopter, true},  {"AS3",  K::Helicopter, true},
        {"AS5",  K::Helicopter, true},  {"AS6",  K::Helicopter, true},
        {"A109", K::Helicopter, false}, {"A119", K::Helicopter, false},
        {"A139", K::Helicopter, false}, {"A169", K::Helicopter, false},
        {"A189", K::Helicopter, false}, {"AW",   K::Helicopter, true},
        {"B06",  K::Helicopter, false}, {"B407", K::Helicopter, false},
        {"B412", K::Helicopter, false}, {"B429", K::Helicopter, false},
        {"R22",  K::Helicopter, false}, {"R44",  K::Helicopter, false},
        {"R66",  K::Helicopter, false}, {"S76",  K::Helicopter, false},
        {"S92",  K::Helicopter, false}, {"H60",  K::Helicopter, false},
        {"H160", K::Helicopter, false}, {"H47",  K::Helicopter, false},
        {"NH90", K::Helicopter, false}, {"EH10", K::Helicopter, false},
        {"MI8",  K::Helicopter, false}, {"GAZL", K::Helicopter, false},
        // Light aircraft (pistons)
        {"C15",  K::LightAircraft, true}, {"C17",  K::LightAircraft, true},
        {"C18",  K::LightAircraft, true}, {"C20",  K::LightAircraft, true},
        {"C21",  K::LightAircraft, true}, {"C310", K::LightAircraft, false},
        {"P28",  K::LightAircraft, true}, {"PA",   K::LightAircraft, true},
        {"P32",  K::LightAircraft, true}, {"SR2",  K::LightAircraft, true},
        {"DA4",  K::LightAircraft, true}, {"DA2",  K::LightAircraft, true},
        {"DV20", K::LightAircraft, false}, {"BE3",  K::LightAircraft, true},
        {"BE5",  K::LightAircraft, true}, {"BE76", K::LightAircraft, false},
        {"TB",   K::LightAircraft, true}, {"M20",  K::LightAircraft, true},
        {"AA5",  K::LightAircraft, false}, {"RV",   K::LightAircraft, true},
        {"CH7",  K::LightAircraft, true}, {"C42",  K::LightAircraft, false},
        {"TOBA", K::LightAircraft, false}, {"SIRA", K::LightAircraft, false},
    };

    bool matches(const TypeRule &r, const char *code)
    {
        if (r.prefix) return strncmp(code, r.code, strlen(r.code)) == 0;
        return strcmp(code, r.code) == 0;
    }

    const Rgb kBody     {235, 240, 245};
    const Rgb kBelly    {165, 172, 185};
    const Rgb kWindow   { 90, 170, 255};
    const Rgb kCockpit  { 40,  60,  90};
    const Rgb kWing     {125, 132, 145};
    const Rgb kEngine   { 70,  75,  85};
    const Rgb kCowl     {190, 195, 205};
    const Rgb kProp     {150, 155, 165};
    const Rgb kGreyBody {150, 155, 165};
    const Rgb kGreyMid  {110, 115, 125};
    const Rgb kGreyDark { 75,  80,  90};
}

const AircraftSprites::Sprite &AircraftSprites::get(Kind k)
{
    return kSprites[k < KindCount ? k : Narrowbody];
}

AircraftSprites::Kind AircraftSprites::classify(const String &icaoType, bool &known)
{
    // Trimmed, upper-cased copy in a stack buffer (called every frame).
    char code[8];
    size_t n = 0;
    for (size_t i = 0; i < icaoType.length() && n + 1 < sizeof(code); ++i)
        if (!isspace((unsigned char)icaoType[i])) code[n++] = (char)toupper((unsigned char)icaoType[i]);
    code[n] = '\0';
    // Exact matches win over prefixes, so A318/A319 aren't caught by "A31".
    for (const TypeRule &r : kRules)
        if (!r.prefix && matches(r, code)) { known = true; return r.kind; }
    for (const TypeRule &r : kRules)
        if (r.prefix && matches(r, code)) { known = true; return r.kind; }
    known = false;
    return Narrowbody;
}

void AircraftSprites::draw(FrameCanvas &c, const Sprite &s, int x, int y, Rgb tail,
                           bool flipX, bool grey, bool outline)
{
    auto at = [&](int r, int col) -> char {
        if (r < 0 || r >= s.h || col < 0 || col >= s.w) return '.';
        return s.rows[r][flipX ? s.w - 1 - col : col];
    };

    // Outline: a solid black backing so whatever the sprite passes over can't
    // show through it. Each row is cleared from the leftmost to the rightmost
    // pixel of the sprite in that row and its neighbours (1px halo all round),
    // which also fills the gaps between engines, wings and tail.
    if (outline)
        for (int r = -1; r <= s.h; ++r)
        {
            int first = s.w, last = -1;
            for (int dy = -1; dy <= 1; ++dy)
                for (int col = 0; col < s.w; ++col)
                    if (at(r + dy, col) != '.')
                    {
                        first = min(first, col);
                        last  = max(last, col);
                    }
            for (int col = first - 1; col <= last + 1; ++col)
                c.set(x + col, y + r, (uint16_t)0);
        }

    for (int r = 0; r < s.h; ++r)
        for (int col = 0; col < s.w; ++col)
        {
            Rgb px;
            switch (at(r, col))
            {
                case '#': px = grey ? kGreyBody : kBody;    break;
                case '+': px = grey ? kGreyMid  : kBelly;   break;
                case 'w': px = grey ? kGreyDark : kWindow;  break;
                case 'c': px = grey ? kGreyDark : kCockpit; break;
                case 'r': px = grey ? kGreyBody : tail;     break;
                case 'R': px = grey ? kGreyMid  : FrameCanvas::scale(tail, 0.6f); break;
                case 'g': px = grey ? kGreyDark : kWing;    break;
                case 'd': px = grey ? kGreyDark : kEngine;  break;
                case 'e': px = grey ? kGreyMid  : kCowl;    break;
                case 'p': px = grey ? kGreyDark : kProp;    break;
                default:  continue;
            }
            c.set(x + col, y + r, px);
        }
}
