#include "display/LandingScene.h"
#include <math.h>

namespace
{
    // Timeline (ms)
    constexpr uint32_t kTouchdownMs = 1100;   // end of the approach and flare
    constexpr uint32_t kStoppedMs   = 2900;   // end of the rollout
    constexpr uint32_t kSmokeMs     = 750;    // tyre smoke lifetime

    // Geometry (right-to-left; mirrored for the other direction)
    constexpr int kSurfaceY   = 58;           // runway surface rows 58-61
    constexpr int kKeysX      = 100;          // threshold piano keys x 100-108
    constexpr int kLightsX0   = 112;          // approach lights x 112-124
    constexpr int kTouchdownX = 84;           // sprite centre at touchdown
    constexpr int kStopX      = 24;           // sprite centre when stopped
    constexpr int kEntryY     = 14;           // sprite top on entry

    const Rgb kSurface   { 26,  28,  34};
    const Rgb kEdge      { 70,  74,  82};
    const Rgb kCentre    {150, 150, 155};
    const Rgb kKeys      {215, 215, 220};
    const Rgb kLightDim  {140,  92,  25};
    const Rgb kLightHead {255, 255, 255};
    const Rgb kText      {235, 240, 245};

    // London skyline on the horizon (generated by tools/skyline_workbench.py):
    // Elizabeth Tower, London Eye, St Paul's, Gherkin, Walkie-Talkie, Shard.
    // '#' silhouette, 'w' lit window, 'r' aviation warning light.
    const char *const kSkyline[] = {
        "......................................................................................r.........................................",
        "......................................................................................#.........................................",
        "......................................................................................#.........................................",
        "......................................................................................#.........................................",
        ".....................#######.........................................................###........................................",
        "......#............##...#...#........................................................###........................................",
        "......#...........##.........##......................................................###........................................",
        ".....###.........##.....#.....##.....................................................###........................................",
        ".....###........##.............##....................................................###........................................",
        ".....###........#...#...#...#...#.............#...............#.....................#w###.......................................",
        ".....###.......#.....#.....#.....#...........###.............###....................#####.......................................",
        ".....###.......#........#........#............#.............#####...................#####.......................................",
        "....#####......#.......#.#.......#..........#####...........#####...................#####.......................................",
        "....##w##......##.#.#.#####.#.#.##.........#######.........#######.###########......##w##.......................................",
        "....#####......#.......#.#.......#.........#######.........##w####.###########......#####.......................................",
        "....#####......#.......###.......#.........#######.........####w##.###########.....#######.....####.............................",
        ".....###.......#.....##...##.....#.........#######.........#######..#########......#######.....####.............................",
        ".....###........#...#.#.#.#.#...#........###########.......#######..#########......##w####.....####.............................",
        ".....###........##....#...#....##........###########.......##w####..#########......#######.....####..###........................",
        ".....###.........##..#..#..#..##.........###########.......####w##..#########......#######.....####..###........................",
        ".....###..........##.#.....#####.........###########.......#######..#########.....#########....####..###.............#####......",
        ".....###......####..##..#..#####.......#############..###...#####...########......####w####....####..#######.........#####......",
        "...######.....######################...##################...#w###################.#########..######..##########......#########..",
        "###############################################################w################################################################",
        "#w########w########w########w########w########w########w########w########w########w########w########w########w########w########w",
        "################################################################################################################################",
    };
    constexpr int kSkylineRows = sizeof(kSkyline) / sizeof(kSkyline[0]);
    const Rgb kSilhouette { 40,  45,  62};
    const Rgb kWindowLit  {150, 110,  40};
    const Rgb kWarning    {230,  40,  40};

    // Drawn pre-mirrored when the scene will be mirrored, so London never
    // appears back to front. Bottom row sits on the runway edge line.
    void drawSkyline(FrameCanvas &c, uint32_t tMs, bool mirrored)
    {
        const int top = kSurfaceY - kSkylineRows;
        const bool lightOn = (tMs / 600) % 2 == 0;
        for (int r = 0; r < kSkylineRows; ++r)
            for (int x = 0; x < FrameCanvas::W; ++x)
            {
                const char ch = kSkyline[r][x];
                if (ch == '.') continue;
                const int px = mirrored ? FrameCanvas::W - 1 - x : x;
                if (ch == 'r')      { if (lightOn) c.set(px, top + r, kWarning); }
                else if (ch == 'w') c.set(px, top + r, kWindowLit);
                else                c.set(px, top + r, kSilhouette);
            }
    }

    float easeOut(float u) { u = u < 0 ? 0 : (u > 1 ? 1 : u); return 1 - (1 - u) * (1 - u); }

    void mirror(FrameCanvas &c)
    {
        uint16_t *p = c.pixels();
        for (int y = 0; y < FrameCanvas::H; ++y)
            for (int x = 0; x < FrameCanvas::W / 2; ++x)
            {
                uint16_t &a = p[y * FrameCanvas::W + x];
                uint16_t &b = p[y * FrameCanvas::W + FrameCanvas::W - 1 - x];
                const uint16_t t = a; a = b; b = t;
            }
    }
}

void LandingScene::render(FrameCanvas &c, uint32_t tMs, const AircraftSprites::Sprite &sp,
                          Rgb accent, bool greySprite, bool rightward,
                          const String &ident, const char *runway)
{
    c.clear();
    drawSkyline(c, tMs, rightward);

    // Runway: surface, dotted edge line, dashed centreline, piano keys.
    for (int y = kSurfaceY; y <= kSurfaceY + 3; ++y)
        for (int x = 0; x < kKeysX + 9; ++x)
            c.set(x, y, kSurface);
    for (int x = 0; x < kKeysX + 9; x += 2) c.set(x, kSurfaceY - 1, kEdge);
    for (int x = 2; x < kKeysX - 4; ++x)
        if ((x / 4) % 2 == 0) c.set(x, kSurfaceY + 2, kCentre);
    for (int x = kKeysX; x <= kKeysX + 8; x += 2)
        for (int y = kSurfaceY; y <= kSurfaceY + 3; ++y)
            c.set(x, y, kKeys);

    // Approach lights chasing towards the threshold.
    const int nLights = (FrameCanvas::W - 4 - kLightsX0) / 4 + 1;
    const int head = (int)((tMs / 70) % (nLights + 2));
    for (int j = 0; j < nLights; ++j)
    {
        const int x = FrameCanvas::W - 4 - j * 4;
        const Rgb col = j == head ? kLightHead : kLightDim;
        c.set(x, kSurfaceY + 2, col);
        c.set(x + 1, kSurfaceY + 2, col);
    }

    // Aircraft position: approach + flare, then rollout.
    const int groundTop = kSurfaceY - 1 - sp.h;          // sprite resting just above the surface
    float cx, top;
    if (tMs < kTouchdownMs)
    {
        const float u = (float)tMs / kTouchdownMs;
        const float startCx = FrameCanvas::W + sp.w / 2.0f + 2;
        cx  = startCx + u * (kTouchdownX - startCx);
        top = kEntryY + easeOut(u) * (groundTop - kEntryY);   // steep then flaring
    }
    else
    {
        const float u = (float)(tMs - kTouchdownMs) / (kStoppedMs - kTouchdownMs);
        cx  = kTouchdownX - easeOut(u) * (kTouchdownX - kStopX);
        top = groundTop;
    }

    // Tyre smoke where the wheels touched, drifting slightly and fading.
    if (tMs >= kTouchdownMs && tMs < kTouchdownMs + kSmokeMs)
    {
        const float age  = (float)(tMs - kTouchdownMs) / kSmokeMs;
        const float fade = 1.0f - age;
        const int   r    = 1 + (int)(age * 4);
        const int   wheels = kTouchdownX + sp.w / 6;
        const int   puffs[][2] = { {0, 0}, {4, -1}, {8, 0}, {11, -2} };
        for (const auto &pf : puffs)
        {
            const int px = wheels + pf[0] + (int)(age * 4), py = kSurfaceY - 2 + pf[1] - (int)(age * 2);
            for (int dy = -r; dy <= r; ++dy)
                for (int dx = -r; dx <= r; ++dx)
                    if (dx * dx + dy * dy <= r * r)
                        c.set(px + dx, py + dy, FrameCanvas::scale(Rgb{210, 210, 215}, fade * 0.8f));
        }
    }

    AircraftSprites::draw(c, sp, (int)lroundf(cx - sp.w / 2.0f), (int)lroundf(top),
                          accent, false, greySprite, true);

    if (rightward) mirror(c);

    // Caption once the wheels are down.
    if (tMs >= kTouchdownMs)
    {
        const float k = min(1.0f, (float)(tMs - kTouchdownMs) / 250.0f);
        char line1[16];
        snprintf(line1, sizeof(line1), runway && runway[0] ? "LANDED %s" : "LANDED", runway);
        c.text((FrameCanvas::W - FrameCanvas::textWidth(line1)) / 2, 6, line1, FrameCanvas::scale(accent, k));
        c.text((FrameCanvas::W - FrameCanvas::textWidth(ident)) / 2, 17, ident, FrameCanvas::scale(kText, k));
    }
}
