#include "display/LandingScene.h"
#include "config/Airport.h"
#include <math.h>

namespace
{
    // Timeline (ms)
    constexpr uint32_t kTouchdownMs = 1100;   // end of the approach and flare
    constexpr uint32_t kStoppedMs   = 2900;   // end of the rollout
    constexpr uint32_t kSmokeMs     = 750;    // tyre smoke lifetime
    constexpr uint32_t kGoAroundAtMs = 950;   // go-around: when it pitches up
    constexpr uint32_t kLiftOffMs   = 1700;   // take-off: end of the ground roll

    // Geometry (right-to-left; mirrored for the other direction)
    constexpr int kSurfaceY   = 58;           // runway surface rows 58-61
    constexpr int kKeysX      = 100;          // threshold piano keys x 100-108
    constexpr int kLightsX0   = 112;          // approach lights x 112-124
    constexpr int kTouchdownX = 84;           // sprite centre at touchdown
    constexpr int kStopX      = 24;           // sprite centre when stopped
    constexpr int kEntryY     = 14;           // sprite top on entry

    const Rgb kSurface   { 26,  28,  34};
    const Rgb kEdge      { 70,  74,  82};
    const Rgb kCentre    {150, 150, 155};
    const Rgb kKeys      {215, 215, 220};
    const Rgb kLightDim  {140,  92,  25};
    const Rgb kLightHead {255, 255, 255};
    const Rgb kText      {235, 240, 245};

    // London skyline on the horizon (generated by tools/skyline_workbench.py):
    // Elizabeth Tower, London Eye, St Paul's, Gherkin, Walkie-Talkie, Shard.
    // '#' silhouette, 'w' lit window, 'r' aviation warning light.
    const char *const kSkyline[] = {
        "......................................................................................r.........................................",
        "......................................................................................#.........................................",
        "......................................................................................#.........................................",
        "......................................................................................#.........................................",
        ".....................#######.........................................................###........................................",
        "......#............##...#...#........................................................###........................................",
        "......#...........##.........##......................................................###........................................",
        ".....###.........##.....#.....##.....................................................###........................................",
        ".....###........##.............##....................................................###........................................",
        ".....###........#...#...#...#...#.............#...............#.....................#w###.......................................",
        ".....###.......#.....#.....#.....#...........###.............###....................#####.......................................",
        ".....###.......#........#........#............#.............#####...................#####.......................................",
        "....#####......#.......#.#.......#..........#####...........#####...................#####.......................................",
        "....##w##......##.#.#.#####.#.#.##.........#######.........#######.###########......##w##.......................................",
        "....#####......#.......#.#.......#.........#######.........##w####.###########......#####.......................................",
        "....#####......#.......###.......#.........#######.........####w##.###########.....#######.....####.............................",
        ".....###.......#.....##...##.....#.........#######.........#######..#########......#######.....####.............................",
        ".....###........#...#.#.#.#.#...#........###########.......#######..#########......##w####.....####.............................",
        ".....###........##....#...#....##........###########.......##w####..#########......#######.....####..###........................",
        ".....###.........##..#..#..#..##.........###########.......####w##..#########......#######.....####..###........................",
        ".....###..........##.#.....#####.........###########.......#######..#########.....#########....####..###.............#####......",
        ".....###......####..##..#..#####.......#############..###...#####...########......####w####....####..#######.........#####......",
        "...######.....######################...##################...#w###################.#########..######..##########......#########..",
        "###############################################################w################################################################",
        "#w########w########w########w########w########w########w########w########w########w########w########w########w########w########w",
        "################################################################################################################################",
    };
    constexpr int kSkylineRows = sizeof(kSkyline) / sizeof(kSkyline[0]);
    const Rgb kSilhouetteNight { 40,  45,  62};
    const Rgb kWindowLitNight  {150, 110,  40};
    // This frame's scenery colours (from the sky).
    Rgb  kSilhouette = kSilhouetteNight;
    Rgb  kWindowLit  = kWindowLitNight;
    Rgb  s_hills{26, 30, 42}, s_roof{58, 64, 82};
    bool s_windows = true;

    // Captions get a dark shadow when there is sky behind them.
    bool s_shadow = false;
    void caption(FrameCanvas &c, int y, const char *s, Rgb col)
    {
        const int x = (FrameCanvas::W - FrameCanvas::textWidth(s)) / 2;
        if (s_shadow) c.text(x + 1, y + 1, s, Rgb{0, 0, 0});
        c.text(x, y, s, col);
    }

    // Aircraft lights after dark: landing light and its beam ahead of the
    // nose, a red beacon on top, white strobes. Drawn for leftward travel.
    void drawAircraftLights(FrameCanvas &c, int left, int top, int w, int h, uint32_t tMs,
                            float slope, bool landingLight)
    {
        const int noseY = top + (h * 3) / 5;
        if (landingLight)
        {
            c.set(left, noseY, Rgb{255, 255, 235});
            for (int i = 1; i <= 10; ++i)
            {
                const float k = 0.55f * (1.0f - i / 11.0f);
                const int y = noseY + (int)lroundf(i * slope);
                for (int dy = -(i / 4); dy <= i / 4; ++dy)
                {
                    const Rgb under = FrameCanvas::unpack(c.get(left - i, y + dy));
                    c.set(left - i, y + dy, Rgb{(uint8_t)min(255, under.r + (int)(230 * k)),
                                                (uint8_t)min(255, under.g + (int)(225 * k)),
                                                (uint8_t)min(255, under.b + (int)(190 * k))});
                }
            }
        }
        if ((tMs + 300) % 1200 < 120) c.set(left + w / 2, top, Rgb{255, 40, 30});        // beacon
        if (tMs % 1000 < 60 || (tMs % 1000 > 140 && tMs % 1000 < 200))
            c.set(left + w - 2, top + h / 3, Rgb{255, 255, 255});                         // strobe
    }
    const Rgb kWarning    {230,  40,  40};

    // Drawn pre-mirrored when the scene will be mirrored, so London never
    // appears back to front. Bottom row sits on the runway edge line.
    void drawSkyline(FrameCanvas &c, uint32_t tMs, bool mirrored)
    {
        const int top = kSurfaceY - kSkylineRows;
        const bool lightOn = (tMs / 600) % 2 == 0;
        for (int r = 0; r < kSkylineRows; ++r)
            for (int x = 0; x < FrameCanvas::W; ++x)
            {
                const char ch = kSkyline[r][x];
                if (ch == '.') continue;
                const int px = mirrored ? FrameCanvas::W - 1 - x : x;
                if (ch == 'r')      { if (lightOn) c.set(px, top + r, kWarning); }
                else if (ch == 'w') c.set(px, top + r, s_windows ? kWindowLit : kSilhouette);
                else                c.set(px, top + r, kSilhouette);
            }
    }

    // Any other airport: rolling hills, a tree line, hangars, a terminal
    // with lit windows and a control tower whose beacon flashes green and
    // white (as real aerodrome beacons do). Drawn procedurally, pre-mirrored
    // like the London one; its base sits on the runway edge line.
    void drawGenericSkyline(FrameCanvas &c, uint32_t tMs, bool mirrored)
    {
        const int base = kSurfaceY - 1;
        auto put = [&](int x, int y, Rgb col) {
            if (x < 0 || x >= FrameCanvas::W) return;
            c.set(mirrored ? FrameCanvas::W - 1 - x : x, y, col);
        };
        const Rgb hills = s_hills;
        for (int x = 0; x < FrameCanvas::W; ++x)
        {
            const int h = 3 + (int)lroundf(2.0f * sinf(x * 0.045f) + 1.5f * sinf(x * 0.11f + 1.3f));
            for (int y = base - h; y < base; ++y) put(x, y, hills);
            // Tree line: clumps of 1-3 px on the hills.
            const int t = (x * 37 + 11) % 23 < 9 ? 1 + ((x * 13) % 3) : 0;
            for (int y = base - h - t; y < base - h; ++y) put(x, y, kSilhouette);
        }
        // Hangars: boxes with a lighter roof line.
        const int hangars[][3] = { {8, 18, 7}, {28, 14, 6} };   // x, width, height
        for (const auto &hg : hangars)
        {
            for (int y = base - hg[2]; y < base; ++y)
                for (int x = hg[0]; x < hg[0] + hg[1]; ++x) put(x, y, kSilhouette);
            for (int x = hg[0]; x < hg[0] + hg[1]; ++x) put(x, base - hg[2], s_roof);
        }
        // Terminal: long and low, two rows of windows.
        for (int y = base - 6; y < base; ++y)
            for (int x = 88; x < 124; ++x) put(x, y, kSilhouette);
        const Rgb win = s_windows ? kWindowLit : FrameCanvas::scale(kSilhouette, 0.8f);
        for (int x = 90; x < 122; x += 2) { put(x, base - 4, win); if (x % 6) put(x, base - 2, win); }
        // Control tower: shaft, flared cab with windows, beacon on top.
        const int tx = 70;
        for (int y = base - 18; y < base; ++y)
            for (int x = tx - 1; x <= tx + 1; ++x) put(x, y, kSilhouette);
        for (int y = base - 23; y < base - 18; ++y)
            for (int x = tx - 4; x <= tx + 4; ++x) put(x, y, kSilhouette);
        for (int x = tx - 3; x <= tx + 3; ++x) put(x, base - 21, Rgb{70, 140, 150});
        put(tx, base - 24, kSilhouette);
        const uint32_t phase = tMs % 1200;
        if (phase < 150)                     put(tx, base - 25, Rgb{60, 255, 120});    // green ...
        else if (phase >= 600 && phase < 750) put(tx, base - 25, Rgb{255, 255, 255});  // ... then white
    }

    float easeOut(float u) { u = u < 0 ? 0 : (u > 1 ? 1 : u); return 1 - (1 - u) * (1 - u); }

    void mirror(FrameCanvas &c)
    {
        uint16_t *p = c.pixels();
        for (int y = 0; y < FrameCanvas::H; ++y)
            for (int x = 0; x < FrameCanvas::W / 2; ++x)
            {
                uint16_t &a = p[y * FrameCanvas::W + x];
                uint16_t &b = p[y * FrameCanvas::W + FrameCanvas::W - 1 - x];
                const uint16_t t = a; a = b; b = t;
            }
    }
}

void LandingScene::render(FrameCanvas &c, uint32_t tMs, const AircraftSprites::Sprite &sp,
                          Rgb accent, bool greySprite, bool rightward,
                          const char *ident, const char *runway, Kind kind, const Sky::Look &sky)
{
    const bool goAround = kind == GoAround, takeoff = kind == Takeoff;
    c.clear();
    Sky::drawSky(c, sky, tMs, kSurfaceY - 1);
    kSilhouette = Sky::shade(sky, kSilhouetteNight);
    kWindowLit  = kWindowLitNight;
    s_hills     = Sky::shade(sky, Rgb{26, 30, 42});
    s_roof      = Sky::shade(sky, Rgb{58, 64, 82});
    s_windows   = !sky.known || sky.lightsOn;
    s_shadow    = sky.known && sky.night < 0.6f;
    if (g_airport.londonSkyline) drawSkyline(c, tMs, rightward);
    else                         drawGenericSkyline(c, tMs, rightward);

    // Runway: surface, dotted edge line, dashed centreline, piano keys.
    for (int y = kSurfaceY; y <= kSurfaceY + 3; ++y)
        for (int x = 0; x < kKeysX + 9; ++x)
            c.set(x, y, kSurface);
    const Rgb edge = sky.known && sky.lightsOn ? Rgb{235, 215, 150} : kEdge;
    for (int x = 0; x < kKeysX + 9; x += (sky.known && sky.lightsOn ? 4 : 2)) c.set(x, kSurfaceY - 1, edge);
    for (int x = 2; x < kKeysX - 4; ++x)
        if ((x / 4) % 2 == 0) c.set(x, kSurfaceY + 2, kCentre);
    for (int x = kKeysX; x <= kKeysX + 8; x += 2)
        for (int y = kSurfaceY; y <= kSurfaceY + 3; ++y)
            c.set(x, y, kKeys);

    // Approach lights chasing towards the threshold.
    const int nLights = (FrameCanvas::W - 4 - kLightsX0) / 4 + 1;
    const int head = (int)((tMs / 70) % (nLights + 2));
    for (int j = 0; j < nLights; ++j)
    {
        const int x = FrameCanvas::W - 4 - j * 4;
        const Rgb col = (j == head && !takeoff) ? kLightHead : kLightDim;
        c.set(x, kSurfaceY + 2, col);
        c.set(x + 1, kSurfaceY + 2, col);
    }

    // Aircraft position: approach + flare, then rollout.
    const int groundTop = kSurfaceY - 1 - sp.h;          // sprite resting just above the surface
    float cx, top;
    if (takeoff)
    {
        // Lined up just past the piano keys, accelerating along the runway,
        // rotating and climbing out over the skyline.
        const float startCx = kKeysX - 4 - sp.w / 2.0f;
        const float liftCx  = 46;
        if (tMs < kLiftOffMs)
        {
            const float u = (float)tMs / kLiftOffMs;
            cx  = startCx - u * u * (startCx - liftCx);                   // speeding up
            top = groundTop;
        }
        else
        {
            const float u    = (float)(tMs - kLiftOffMs) / (DURATION_MS - kLiftOffMs);
            const float pace = 2.0f * (startCx - liftCx) / kLiftOffMs;    // px per ms at lift-off
            cx  = liftCx - pace * (tMs - kLiftOffMs);
            top = groundTop - u * u * (groundTop + sp.h + 4) - u * 6;     // climbing, steepening
        }

        // Spray of dust and heat behind the engines during the roll.
        if (tMs < kLiftOffMs + 300)
        {
            const float k = tMs < kLiftOffMs ? (float)tMs / kLiftOffMs : 1.0f - (tMs - kLiftOffMs) / 300.0f;
            const int tail = (int)lroundf(cx + sp.w / 2.0f);
            for (int i = 0; i < 6; ++i)
            {
                const int px = tail + 2 + i * 3 + (int)((tMs / 40 + i) % 3);
                const int py = kSurfaceY - 2 - (i % 2);
                c.set(px, py, FrameCanvas::scale(Rgb{170, 170, 175}, k * (1.0f - i / 6.0f) * 0.7f));
            }
        }
    }
    else if (goAround)
    {
        // Comes down towards the threshold, then pitches up and climbs away
        // over the skyline, never touching the runway.
        const float startCx = FrameCanvas::W + sp.w / 2.0f + 2;
        const float lowest  = groundTop - 7;
        const float pace    = (kTouchdownX - startCx) / kTouchdownMs;     // px per ms on the approach
        if (tMs < kGoAroundAtMs)
        {
            const float u = (float)tMs / kGoAroundAtMs;
            cx  = startCx + pace * tMs;
            top = kEntryY + easeOut(u) * (lowest - kEntryY);
        }
        else
        {
            const float u = (float)(tMs - kGoAroundAtMs) / (DURATION_MS - kGoAroundAtMs);
            cx  = startCx + pace * tMs;                                    // keeps flying along
            top = lowest - u * u * (lowest + sp.h + 4);                    // climb, steepening
        }
    }
    else if (tMs < kTouchdownMs)
    {
        const float u = (float)tMs / kTouchdownMs;
        const float startCx = FrameCanvas::W + sp.w / 2.0f + 2;
        cx  = startCx + u * (kTouchdownX - startCx);
        top = kEntryY + easeOut(u) * (groundTop - kEntryY);   // steep then flaring
    }
    else
    {
        const float u = (float)(tMs - kTouchdownMs) / (kStoppedMs - kTouchdownMs);
        cx  = kTouchdownX - easeOut(u) * (kTouchdownX - kStopX);
        top = groundTop;
    }

    // Tyre smoke where the wheels touched, drifting slightly and fading.
    if (kind == Landing && tMs >= kTouchdownMs && tMs < kTouchdownMs + kSmokeMs)
    {
        const float age  = (float)(tMs - kTouchdownMs) / kSmokeMs;
        const float fade = 1.0f - age;
        const int   r    = 1 + (int)(age * 4);
        const int   wheels = kTouchdownX + sp.w / 6;
        const int   puffs[][2] = { {0, 0}, {4, -1}, {8, 0}, {11, -2} };
        for (const auto &pf : puffs)
        {
            const int px = wheels + pf[0] + (int)(age * 4), py = kSurfaceY - 2 + pf[1] - (int)(age * 2);
            for (int dy = -r; dy <= r; ++dy)
                for (int dx = -r; dx <= r; ++dx)
                    if (dx * dx + dy * dy <= r * r)
                        c.set(px + dx, py + dy, FrameCanvas::scale(Rgb{210, 210, 215}, fade * 0.8f));
        }
    }

    AircraftSprites::draw(c, sp, (int)lroundf(cx - sp.w / 2.0f), (int)lroundf(top),
                          accent, false, greySprite, true);

    if (sky.known && sky.lightsOn)
    {
        // Beam slope: down on the approach, level on the ground, up in a climb.
        float slope = 0;
        bool  landingLight = true;
        if (takeoff)        slope = tMs < kLiftOffMs ? 0.0f : -0.35f;
        else if (goAround)  slope = tMs < kGoAroundAtMs ? 0.45f : -0.4f;
        else if (tMs < kTouchdownMs) slope = 0.45f;
        else landingLight = tMs < kStoppedMs - 300;   // off as it slows to taxi
        drawAircraftLights(c, (int)lroundf(cx - sp.w / 2.0f), (int)lroundf(top), sp.w, sp.h, tMs,
                           slope, landingLight);
    }
    Sky::drawWeather(c, sky, tMs);

    if (rightward) mirror(c);

    // Go-around caption: flashing red once it starts to climb.
    if (goAround && tMs >= kGoAroundAtMs)
    {
        char line1[16];
        snprintf(line1, sizeof(line1), "GO AROUND");
        const Rgb red = (tMs / 250) % 2 ? Rgb{255, 70, 60} : Rgb{255, 255, 255};
        caption(c, 6, line1, red);
        caption(c, 17, ident, kText);
        return;
    }

    // Take-off caption once airborne.
    if (takeoff && tMs >= kLiftOffMs)
    {
        const float k = min(1.0f, (float)(tMs - kLiftOffMs) / 250.0f);
        char line1[16];
        snprintf(line1, sizeof(line1), runway && runway[0] ? "DEPARTED %s" : "DEPARTED", runway);
        caption(c, 6, line1, FrameCanvas::scale(accent, k));
        caption(c, 17, ident, FrameCanvas::scale(kText, k));
        return;
    }

    // Caption once the wheels are down.
    if (kind == Landing && tMs >= kTouchdownMs)
    {
        const float k = min(1.0f, (float)(tMs - kTouchdownMs) / 250.0f);
        char line1[16];
        snprintf(line1, sizeof(line1), runway && runway[0] ? "LANDED %s" : "LANDED", runway);
        caption(c, 6, line1, FrameCanvas::scale(accent, k));
        caption(c, 17, ident, FrameCanvas::scale(kText, k));
    }
}
