#!/usr/bin/env python3
"""
Generate firmware/config/AirlineCodes.h: ICAO airline designator -> IATA code,
used to turn call signs into flight-number style idents (BAW487E -> BA487E).

Source: AIRLINE_LIST in tools/build_logos_local.py, plus the overrides below
for sub-fleets that sell their flights under the parent's code.

Usage:  python tools/gen_airline_codes.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'tools' / 'build_logos_local.py'
OUT = ROOT / 'firmware' / 'config' / 'AirlineCodes.h'

# Sub-fleets whose flights are marketed under the parent airline's IATA code.
OVERRIDES = {
    'SHT': 'BA',   # BA Shuttle
    'CFE': 'BA',   # BA CityFlyer (own IATA code CJ, but flights are sold as BA)
    'EFW': 'BA',   # BA Euroflyer
}

text = SRC.read_text(encoding='utf-8')
start = text.index('AIRLINE_LIST = [')
end = text.index('\n]', start)
pairs = dict(re.findall(r'\("([A-Z0-9]{3})",\s*"([A-Z0-9]{2})"', text[start:end]))
pairs.update(OVERRIDES)

rows = '\n'.join(f'    {{"{icao}", "{iata}"}},' for icao, iata in sorted(pairs.items()))
OUT.write_text(f'''// Generated by tools/gen_airline_codes.py — do not edit by hand.
// ICAO airline designator -> IATA code, {len(pairs)} airlines, sorted by ICAO.
#pragma once
#include <string.h>

struct AirlineCode {{ char icao[4]; char iata[3]; }};

static const AirlineCode kAirlineCodes[] = {{
{rows}
}};

// IATA code for an ICAO airline designator, or nullptr if unknown.
inline const char *airlineIata(const char *icao)
{{
    int lo = 0, hi = (int)(sizeof(kAirlineCodes) / sizeof(kAirlineCodes[0])) - 1;
    while (lo <= hi)
    {{
        const int mid = (lo + hi) / 2;
        const int c = strncmp(icao, kAirlineCodes[mid].icao, 3);
        if (c == 0) return kAirlineCodes[mid].iata;
        if (c < 0) hi = mid - 1; else lo = mid + 1;
    }}
    return nullptr;
}}
''', encoding='utf-8')
print(f'wrote {OUT.relative_to(ROOT)} ({len(pairs)} airlines)')
