#!/usr/bin/env python3
"""
Plane icons for the London map: a top-view airliner silhouette rasterised at
16 headings (every 22.5 deg) into 7x7 bitmaps, supersampled for clean edges.
Writes firmware/display/PlaneIcons.h; pass a folder to also save a preview.

Usage:  python tools/icon_workbench.py [preview_dir]
"""
import math, sys
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'firmware' / 'display' / 'PlaneIcons.h'
N, SS, THRESHOLD = 7, 16, 128

# Silhouette, nose up, in units where the icon spans -3.5..3.5.
FUSE = [(0, -3.4), (0.5, -2.6), (0.5, 2.4), (0, 3.1), (-0.5, 2.4), (-0.5, -2.6)]
WING = [(0.45, -0.5), (3.4, 1.0), (3.4, 1.5), (0.45, 0.5), (-0.45, 0.5), (-3.4, 1.5), (-3.4, 1.0), (-0.45, -0.5)]
TAIL = [(0.35, 2.1), (1.5, 2.9), (1.5, 3.3), (0, 3.0), (-1.5, 3.3), (-1.5, 2.9), (-0.35, 2.1)]

def raster(hdg):
    h = math.radians(hdg); c, s = math.cos(h), math.sin(h)
    big = Image.new('L', (N * SS, N * SS), 0)
    d = ImageDraw.Draw(big)
    for poly in (FUSE, WING, TAIL):
        d.polygon([((x * c - y * s + 3.5) * SS, (x * s + y * c + 3.5) * SS) for x, y in poly], fill=255)
    px = big.resize((N, N), Image.BOX).load()
    lit = {(x, y) for y in range(N) for x in range(N) if px[x, y] >= THRESHOLD}
    fx, fy = math.sin(h), -math.cos(h)
    nose = max(lit, key=lambda p: (p[0] - 3) * fx + (p[1] - 3) * fy)
    return lit, nose

icons = [raster(i * 22.5) for i in range(16)]

rows_c = []
for i, (lit, nose) in enumerate(icons):
    rows = [sum(1 << (6 - x) for x in range(N) if (x, y) in lit) for y in range(N)]
    rows_c.append(f'    {{ {{{", ".join(f"0x{r:02X}" for r in rows)}}}, {nose[0]}, {nose[1]} }},   // {i * 22.5:g} deg')

OUT.write_text(f'''// Generated by tools/icon_workbench.py — do not edit by hand.
// Map plane icons: 7x7 top-view silhouettes at 16 headings (every 22.5 deg).
// Row bit 6 is the leftmost pixel; (noseX, noseY) is the nose pixel.
#pragma once
#include <stdint.h>

namespace PlaneIcons
{{
    struct Icon {{ uint8_t rows[7]; uint8_t noseX, noseY; }};

    static const Icon kIcons[16] = {{
{chr(10).join(rows_c)}
    }};

    // Icon for a true heading in degrees.
    inline const Icon &forHeading(float deg)
    {{
        int i = (int)((deg + 11.25f) / 22.5f) % 16;
        if (i < 0) i += 16;
        return kIcons[i];
    }}
}}
''', encoding='utf-8')

if len(sys.argv) > 1:
    S = 10
    im = Image.new('RGB', (16 * 9 * S, 9 * S), (5, 6, 8))
    dr = ImageDraw.Draw(im)
    for i, (lit, nose) in enumerate(icons):
        for x, y in lit:
            dr.rectangle(((i * 9 + 1 + x) * S, (1 + y) * S, (i * 9 + 1 + x) * S + S - 2, (1 + y) * S + S - 2),
                         fill=(255, 255, 255) if (x, y) == nose else (255, 90, 100))
    im.save(Path(sys.argv[1]) / 'plane_icons.png')
print('wrote', OUT.relative_to(ROOT))
